import {
  Ability,
  Character,
  HitDie,
  CharacterSize,
  Attack,
  Feature,
  Spell,
  Currency,
  Note,
  NoteGroup,
} from '../types';
import { INITIAL_SKILLS, INITIAL_SKILL_BONUSES } from '../constants';

const defaultScores = {
  [Ability.STR]: 10, [Ability.DEX]: 10, [Ability.CON]: 10,
  [Ability.INT]: 10, [Ability.WIS]: 10, [Ability.CHA]: 10,
};
const defaultHitDie = HitDie.d8;
const initialMaxHp = defaultHitDie + Math.floor((defaultScores[Ability.CON] - 10) / 2);

export const defaultCharacterState: Character = {
  name: 'Эльдра',
  race: 'Эльф',
  characterClass: 'Волшебник',
  level: 1,
  experience: 0,
  portraitUrl: '',
  scores: defaultScores,
  skills: INITIAL_SKILLS,
  savingThrowProficiencies: {
    [Ability.STR]: false, [Ability.DEX]: false, [Ability.CON]: false,
    [Ability.INT]: false, [Ability.WIS]: false, [Ability.CHA]: false,
  },
  hitDie: defaultHitDie,
  maxHitPoints: initialMaxHp,
  currentHitPoints: initialMaxHp,
  temporaryHitPoints: 0,
  abilityBonuses: {
    [Ability.STR]: 0, [Ability.DEX]: 0, [Ability.CON]: 0,
    [Ability.INT]: 0, [Ability.WIS]: 0, [Ability.CHA]: 0,
  },
  skillBonuses: INITIAL_SKILL_BONUSES,
  baseAC: 10,
  acAbilitySources: {
    [Ability.STR]: false,
    [Ability.DEX]: true,
    [Ability.CON]: false,
    [Ability.INT]: false,
    [Ability.WIS]: false,
    [Ability.CHA]: false,
  },
  acBonus: 0,
  initiativeBonus: 0,
  proficiencyBonusBonus: 0,
  speedBonus: 0,
  savingThrowBonuses: {
    [Ability.STR]: 0, [Ability.DEX]: 0, [Ability.CON]: 0,
    [Ability.INT]: 0, [Ability.WIS]: 0, [Ability.CHA]: 0,
  },
  attunementSlots: 3,
  attunementItems: [null, null, null],
  inventoryRows: 5,
  inventory: Array(50).fill(null),
  equippedItems: [],
  totalHitDice: 1,
  currentHitDice: 1,
  speed: 30,
  longJumpBonus: 0,
  highJumpBonus: 0,
  size: CharacterSize.Medium,
  features: [] as Feature[],
  featureGroups: [
    { id: 'default', name: 'Особенности', featureIds: [] }
  ],
  passivePerceptionBonus: 0,
  passiveInvestigationBonus: 0,
  passiveInsightBonus: 0,
  maxHpBonus: 0,
  carryCapacityBonus: 0,
  attacks: [] as Attack[],
  globalAttackDiceBonusToHitDice: '',
  globalAttackDiceBonusToDamageDice: '',
  spells: [] as Spell[],
  spellSlots: {
    1: { total: 0, used: 0 }, 2: { total: 0, used: 0 }, 3: { total: 0, used: 0 },
    4: { total: 0, used: 0 }, 5: { total: 0, used: 0 }, 6: { total: 0, used: 0 },
    7: { total: 0, used: 0 }, 8: { total: 0, used: 0 }, 9: { total: 0, used: 0 },
  },
  spellcastingAbility: Ability.INT,
  maxPreparedSpells: 0,
  spellSaveDcBonus: 0,
  spellAttackBonusBonus: 0,
  currency: {
    [Currency.CP]: 0,
    [Currency.SP]: 0,
    [Currency.EP]: 0,
    [Currency.GP]: 0,
    [Currency.PP]: 0,
  },
  notes: [] as Note[],
  noteGroups: [] as NoteGroup[],
  activeNoteId: null,
  tabOrder: ['stats', 'combat', 'inventory', 'features', 'notes'],
  viewMode: 'tabs',
  collapsedTabs: {},
};